### ISSUE TITLE
5.0.5 16135

### ISSUE THREAD

**Issue by SeTM** [Zakamurite/HandleDumperV2#1]
Can't find any handler =(
And after inject dll by CheatEngine wow client hang.

Handlers from .log file not found, for expample SMSG_MESSAGECHAT:
Opcode: c9f jamOffs: 6ebf7fd2 handler: 82d050 handler2: 0

**Comment by Dramacydal** [comment]
i doubt that cheat engine injects correctly
forget about it, here are most of 16135 handlers http://fbe.am/rVX

**Comment by SeTM** [comment]
Big thanks!
